### ISSUE TITLE
tap != click on event order

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [jonpacker/jquery.tap#8] opened 2015-09-25 10:40 UTC
we're getting this issue with a piece of code we moved to mobile using the tap library:

on a desktop, the tap is executed before the mouseup event

on mobile, the mouseup event is fired after the tap

that breaks some visualization logic on our modals.

I wasn't expecting mouseup to happen on mobile browsers. Is there a way within tap to overload the event within jquery and have it fire after the touchend?

**Comment by jonpacker** [comment] 2015-09-25 10:46
`.tap` was designed to specifically replace the `click` event, rather than any `mouse*` events, so the library doesn't take a position on this one way or the other. The mouseup event is being fired here by the browser, not this library.

I'm trying to think of a way to help you, but it seems to me that these two statements are relating the exact same situation: "the tap is executed before the mouseup event", and "the mouseup event is fired after the tap"

**Comment by LorenzoBoccaccia** [comment] 2015-09-25 10:53
sorry, I got the description wrong -_____-"

on desktop, it goes mouseup, tap
on mobile, it goes tap, mouseup

here's a stack trace taken from the two events callbacks
https://i.imgur.com/C24bmyI.png
code is the same for both.

no worries if you can't do anything I'll try to hack a way around

**Comment by jonpacker** [comment] 2015-09-25 11:04
Yeah, so the thing here is that on the desktop, the events happen in this order:

1. mousedown
2. mouseup
3. click

When you use `tap` on the desktop, you are just adding a listener for `click`. But on a mobile, you get this:

1. touchstart
2. touchend
3. mousedown
4. mouseup
5. click

`tap` uses the `touchstart` and `touchend` events to deduce if the intention of the touch was the same as that of `click`, i.e., the user touched and released in approximately the same location, without dragging the page around. It's a side effect of that that causes these events to happen in a different order, depending on which case is active.

The problem with forcing the tap event to happen after `mouseup` is that you throw out all of advantages this library gives you. You might as well just use the `click` and `mouseup` events. And because the `click` _must_ happen after the mouseup event on the desktop... you're in a tricky situation if you need them to always happen in the same order, unfortunately...

**Closed by jonpacker** 2015-09-25 11:04 UTC

**Comment by LorenzoBoccaccia** [comment] 2015-09-25 11:06
ok thanks I'm documenting on events and it is even worse than that http://stackoverflow.com/questions/14486804/understanding-touch-events thank you for your time
